/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_simplenfast_jaas_NTUser */

#ifndef _Included_org_simplenfast_jaas_NTUser
#define _Included_org_simplenfast_jaas_NTUser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_simplenfast_jaas_NTUser
 * Method:    login0
 * Signature: (Ljava/lang/String;Ljava/lang/String;[C)J
 */
JNIEXPORT jlong JNICALL Java_org_simplenfast_jaas_NTUser_login0
  (JNIEnv *, jobject, jstring, jstring, jcharArray);

/*
 * Class:     org_simplenfast_jaas_NTUser
 * Method:    logout0
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_simplenfast_jaas_NTUser_logout0
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
