include ../../Makefile.constants

ifndef P
$(error P is not set)
endif

OBJS =  ${P}/rdbts.o

LIBS = -lpthread

all: platform ${P}/rdbts

platform:
	@test -d ${P} || mkdir ${P}

${P}/rdbts: ${OBJS} ${LIBCOM} ${LIBRDB}
	${CC} ${DBG} $^ ${LIBS} -o $@

${P}/%.o: %.cpp
	${CC} ${CFLAGS} ${LDFLAGS} ${DBG} ${DEFINES} ${INCL} $^ -o $@

test:
	@test -d db || mkdir db
	@test -d log || mkdir log
	@echo "DBPATH = ${CURDIR}/db" >> rdbts.conf
	@echo "DBNAME = testdb" >> rdbts.conf
	@valgrind --quiet --leak-check=full --show-leak-kinds=all ${P}/rdbts -name "librdb-test-suite" -desc "test suite for librdb" -config rdbts.conf -logpath "${CURDIR}/log" -v

install:

clean:
	@/bin/rm -rf ${OBJS} ${P}/rdbts rdbts.conf db log
