include ../../Makefile.constants

!IFNDEF P
!ERROR P is not set
!ENDIF

OBJS =  $(P)\rdbts.obj

INCL = $(INCLCOM) $(INCLLOG) $(INCLRDB) $(INCLTF)

PDB = $(P)\rdbts.pdb

all: platform $(P)\rdbts.exe

platform:
	@if not exist $(P) mkdir $(P)

$(P)\rdbts.exe: $(OBJS) $(LIBRDB) $(LIBLOG) $(LIBCOM)
	$(CC) $(DBG) /Fd$*.pdb $** /Fe$@

{.}.cpp{$(P)}.obj:
	$(CC) $(CFLAGS) $(DBG) $(DEFINES) $(INCL) /Fd$(PDB) $< /Fo$@

test:
	@if not exist db mkdir db
	@if not exist log mkdir log
	@echo DBPATH = $(MAKEDIR)\db >> rdbts.conf
	@echo DBNAME = testdb >> rdbts.conf
	@$(P)\rdbts.exe -name "librdb-test-suite" -desc "test suite for librdb" -config rdbts.conf -v

install:

clean:
	@del /q $(OBJS) $(PDB) $(P)\rdbts.*
	@if exist rdbts.conf del /q rdbts.conf
	@if exist db rmdir /q /s db
	@if exist log rmdir /q /s log
