include ../../Makefile.constants

ifndef P
$(error P is not set)
endif

LOGTS_OBJS =  ${P}/logts.o
LOGTESTER_OBJS = ${P}/logtester.o

INCL = ${INCLCOM} ${INCLLOG} ${INCLTF}

all: platform ${P}/logts ${P}/logtester

platform:
	@test -d ${P} || mkdir ${P}

${P}/logts: ${LOGTS_OBJS} ${LIBLOG} ${LIBJSON} ${LIBCOM}
	${CC} ${DBG} $^ ${LIBS} -o $@

${P}/logtester: ${LOGTESTER_OBJS} ${LIBLOG} ${LIBJSON} ${LIBCOM}
	${CC} ${DBG} $^ ${LIBS} -o $@

${P}/%.o: %.cpp
	${CC} ${CFLAGS} ${LDFLAGS} ${DBG} ${DEFINES} ${INCL} $^ -o $@

test:
ifeq (${DBG},-g)
	@valgrind --quiet --leak-check=full --show-leak-kinds=all ${P}/logts -name "liblog-test-suite" -desc "test suite for liblog" -v
else
	@${P}/logts -name "liblog-test-suite" -desc "test suite for liblog" -v
endif

install:

clean:
	@/bin/rm -rf ${LOGTS_OBJS} ${LOGTESTER_OBJS} ${P}/logts ${P}/logtester
