include ../../Makefile.constants

!IFNDEF P
!ERROR P is not set
!ENDIF

LOGTS_OBJS =  $(P)\logts.obj
LOGTESTER_OBJS =  $(P)\logtester.obj

INCL = $(INCLCOM) $(INCLLOG) $(INCLTF)

all: platform $(P)\logts.exe  $(P)\logtester.exe

platform:
	@if not exist $(P) mkdir $(P)

$(P)\logts.exe: $(LOGTS_OBJS) $(LIBLOG) $(LIBCOM)
	$(CC) $(DBG) /Fd$*.pdb $** /Fe$@

$(P)\logtester.exe: $(LOGTESTER_OBJS) $(LIBLOG) $(LIBCOM)
	$(CC) $(DBG) /Fd$*.pdb $** /Fe$@

{.}.cpp{$(P)}.obj:
	$(CC) $(CFLAGS) /utf-8 $(DBG) $(DEFINES) $(INCL) $< /Fo$@

test:
	@$(P)\logts.exe -name "liblog-test-suite" -desc "test suite for liblog" -v

install:

clean:
	@del /q $(LOGTS_OBJS) $(LOGTESTER_OBJS) $(P)\*.pdb $(P)\logts.* $(P)\logtester.*
