include ../../Makefile.constants

!IFNDEF P
!ERROR P is not set
!ENDIF

OBJS =  $(P)\logts.obj

INCL = $(INCLCOM) $(INCLLOG) $(INCLTF)

PDB = $(P)\logts.pdb

all: platform $(P)\logts.exe

platform:
	@if not exist $(P) mkdir $(P)

$(P)\logts.exe: $(OBJS) $(LIBLOG) $(LIBCOM)
	$(CC) $(DBG) /Fd$*.pdb $** /Fe$@

{.}.cpp{$(P)}.obj:
	$(CC) $(CFLAGS) /utf-8 $(DBG) $(DEFINES) $(INCL) /Fd$(PDB) $< /Fo$@

test:
	@$(P)\logts.exe -name "liblog-test-suite" -desc "test suite for liblog" -v

install:

clean:
	@del /q $(OBJS) $(PDB) $(P)\logts.*
