include Makefile.constants

DIRS = libcom libjson liblog jdaemon librdb libnet http

all:
	@for I in ${DIRS}; do make -C $${I} -f Makefile.unix all; done

cscope:
	/bin/rm -f cscope.out
	/bin/rm -f cscope.files
	find . -name "*.h" -o -name "*.cpp" > cscope.files
	cscope -b -u -v -icscope.files

install:
	@for I in ${DIRS}; do make -C $${I} -f Makefile.unix install; done

clean: 
	@for I in ${DIRS}; do make -C $${I} -f Makefile.unix clean; done
