include ../Makefile.constants

DIRS = src tests

all:
	@for I in ${DIRS}; do make -C $${I} -f Makefile.unix all; done

install:
	@for I in ${DIRS}; do make -C $${I} -f Makefile.unix install; done

clean: 
	@for I in ${DIRS}; do make -C $${I} -f Makefile.unix clean; done
