include ../Makefile.constants

OBJS =  $(P)\common.obj \
		$(P)\config.obj \
		$(P)\dll.obj \
		$(P)\file.obj \
		$(P)\filesystem.obj \
		$(P)\i18n.obj \
		$(P)\lock.obj \
		$(P)\log.obj \
		$(P)\perftimer.obj \
		$(P)\util.obj

all: platform $(P)\com.lib

platform:
	@if not exist $(P) mkdir $(P)

$(P)\com.lib: $(OBJS)
	$(AR) $(ARFLAGS) $** /OUT:$@

$(OBJS): $(*B).cpp
	$(CC) $(CFLAGS) $(DBG) $(DEFINES) $(INCL) $(*B).cpp /Fo$@

install:

clean:
	del /q $(P)\*
	rmdir $(P)
