include ../Makefile.constants

ifndef P
$(error P is not set)
endif

OBJS =  ${P}/json.o \
	${P}/parser.o \
	${P}/lexer.o \
	${P}/misc.o \
	${P}/utf.o

all: platform ${P}/libjson.so

platform:
	@test -d ${P} || mkdir ${P}

${P}/libjson.so: ${OBJS}
	${LD} ${LDFLAGS} $^ -o $@

${P}/%.o: %.cpp
	${CC} ${CFLAGS} ${LDFLAGS} ${DBG} ${DEFINES} ${INCL} $^ -o $@

install:

clean:
	@/bin/rm -rf ${OBJS} ${P}/libjson.so
