include ../../Makefile.constants

ifndef P
$(error P is not set)
endif

OBJS =  ${P}/logrec.o \
	${P}/logmgr.o \
	${P}/logger.o \
	${P}/flogger.o

INCL = ${INCLCOM} ${INCLLOG} ${INCLJSON}

all: platform ${P}/liblog.a

platform:
	@test -d ${P} || mkdir ${P}

${P}/liblog.a: ${OBJS}
	${AR} ${ARFLAGS} $@ $^

${P}/%.o: %.cpp
	${CC} ${CFLAGS} ${LDFLAGS} ${DBG} ${DEFINES} ${INCL} $^ -o $@

install:

clean:
	@/bin/rm -rf ${OBJS} ${P}/liblog.a
