include ../../Makefile.constants

ifndef P
$(error P is not set)
endif

HOSTADDR_OBJS = ${P}/hostaddr.o

INCL = ${INCLCOM} ${INCLNET} ${INCLLOG}

all: platform ${P}/hostaddr

platform:
	@test -d ${P} || mkdir ${P}

${P}/hostaddr: ${HOSTADDR_OBJS} ${LIBLOG} ${LIBNET} ${LIBCOM}
	${CC} ${DBG} $^ ${LIBS} -o $@

${P}/%.o: %.cpp
	${CC} ${CFLAGS} ${LDFLAGS} ${DBG} ${DEFINES} ${INCL} $^ -o $@

install:

clean:
	@/bin/rm -rf ${HOSTADDR_OBJS} ${P}/hostaddr
