include ../../Makefile.constants

!IFNDEF P
!ERROR P is not set
!ENDIF

NETTS_OBJS = $(P)\netts.obj
HOST_OBJS = $(P)\host.obj
ECHO_OBJS = $(P)\echo.obj

INCL = $(INCLCOM) $(INCLLOG) $(INCLNET) $(INCLSSL) $(INCLTF)

all: platform $(P)\host.exe $(P)\netts.exe $(P)\echo.exe

platform:
	@if not exist $(P) mkdir $(P)

$(P)\host.exe: $(HOST_OBJS) $(LIBNET) $(LIBLOG) $(LIBJSON) $(LIBCOM)
	$(CC) $(DBG) /Fd$*.pdb $** Ws2_32.lib /Fe$@

$(P)\netts.exe: $(NETTS_OBJS) $(LIBNET) $(LIBLOG) $(LIBJSON) $(LIBCOM)
	$(CC) $(DBG) /Fd$*.pdb $** Ws2_32.lib /Fe$@

$(P)\echo.exe: $(ECHO_OBJS) $(LIBNET) $(LIBLOG) $(LIBJSON) $(LIBCOM)
	$(CC) $(DBG) /Fd$*.pdb $** Ws2_32.lib /Fe$@

{.}.cpp{$(P)}.obj:
	$(CC) $(CFLAGS) /utf-8 $(DBG) $(DEFINES) $(INCL) $< /Fo$@

test:
	@$(P)\netts.exe -name "libnet-test-suite" -desc "test suite for libnet" -v

install:

clean:
	@del /q $(HOST_OBJS) $(NETTS_OBJS) $(ECHO_OBJS) $(P)\*.pdb $(P)\host.* $(P)\netts.* $(P)\echo.*
