include ../../Makefile.constants

ifndef P
$(error P is not set)
endif

NETTS_OBJS = ${P}/netts.o
HOST_OBJS = ${P}/host.o
ECHO_OBJS = ${P}/echo.o

INCL = ${INCLCOM} ${INCLNET} ${INCLLOG} ${INCLSSL} ${INCLTF}
LIBS = -ldl -lpthread

all: platform ${P}/host ${P}/netts ${P}/echo

platform:
	@test -d ${P} || mkdir ${P}

${P}/host: ${HOST_OBJS} ${LIBLOG} ${LIBNET} ${LIBCOM}
	${CC} ${DBG} $^ ${LIBS} -o $@

${P}/netts: ${NETTS_OBJS} ${LIBLOG} ${LIBNET} ${LIBCOM}
	${CC} ${DBG} $^ ${LIBS} -o $@

${P}/echo: ${ECHO_OBJS} ${LIBLOG} ${LIBNET} ${LIBCOM}
	${CC} ${DBG} $^ ${LIBS} -o $@

${P}/%.o: %.cpp
	${CC} ${CFLAGS} ${LDFLAGS} ${DBG} ${DEFINES} ${INCL} $^ -o $@

test:
ifeq (${DBG},-g)
	@valgrind --quiet --leak-check=full --show-leak-kinds=definite ${P}/netts -name "libnet-test-suite" -desc "test suite for libnet" -v
else
	@${P}/netts -name "libnet-test-suite" -desc "test suite for libnet" -v
endif

install:

clean:
	@/bin/rm -rf ${HOST_OBJS} ${NETTS_OBJS} ${ECHO_OBJS} ${P}/host ${P}/netts ${P}/echo
