include ../../Makefile.constants

!IFNDEF P
!ERROR P is not set
!ENDIF

HOSTADDR_OBJS =  $(P)\hostaddr.obj

INCL = $(INCLCOM) $(INCLLOG) $(INCLNET)

all: platform $(P)\hostaddr.exe

platform:
	@if not exist $(P) mkdir $(P)

$(P)\hostaddr.exe: $(HOSTADDR_OBJS) $(LIBNET) $(LIBLOG) $(LIBJSON) $(LIBCOM)
	$(CC) $(DBG) /Fd$*.pdb $** Ws2_32.lib /Fe$@

{.}.cpp{$(P)}.obj:
	$(CC) $(CFLAGS) /utf-8 $(DBG) $(DEFINES) $(INCL) $< /Fo$@

install:

clean:
	@del /q $(HOSTADDR_OBJS) $(P)\*.pdb $(P)\hostaddr.*
