include ../../Makefile.constants

!IFNDEF P
!ERROR P is not set
!ENDIF

OBJS =  $(P)\jsonts.obj

INCL = $(INCLCOM) $(INCLJSON) $(INCLTF)

PDB = $(P)\jsonts.pdb

all: platform $(P)\jsonts.exe

platform:
	@if not exist $(P) mkdir $(P)

$(P)\jsonts.exe: $(OBJS) $(LIBJSON) $(LIBCOM)
	$(CC) $(DBG) /Fd$*.pdb $** /Fe$@

{.}.cpp{$(P)}.obj:
	$(CC) $(CFLAGS) /utf-8 $(DBG) $(DEFINES) $(INCL) /Fd$(PDB) $< /Fo$@

test:
	@$(P)\jsonts.exe -name "libjson-test-suite" -desc "test suite for libjson" -v

install:

clean:
	@del /q $(OBJS) $(PDB) $(P)\jsonts.*
