include ../../Makefile.constants

ifndef P
$(error P is not set)
endif

OBJS = ${P}/httpts.o
HTTPSRVR_OBJS = ${P}/httpsrvr.o

INCL = ${INCLHTTPCMN} ${INCLHTTPSRVR} ${INCLCOM} ${INCLNET} ${INCLSSL} ${INCLLOG} ${INCLJSON} ${INCLTF}
LIBS = -ldl -lpthread

all: platform ${P}/httpts ${P}/httpsrvr

platform:
	@test -d ${P} || mkdir ${P}

${P}/httpts: ${OBJS} ${LIBHTTPSRVR} ${LIBHTTPCMN} ${LIBNET} ${LIBLOG} ${LIBJSON} ${LIBCOM}
	${CC} ${DBG} $^ ${LIBS} -o $@

${P}/httpsrvr: ${HTTPSRVR_OBJS} ${LIBHTTPSRVR} ${LIBHTTPCMN} ${LIBNET} ${LIBLOG} ${LIBJSON} ${LIBCOM} 
	${CC} ${DBG} $^ ${LIBS} -o $@

${P}/%.o: %.cpp
	${CC} ${CFLAGS} ${LDFLAGS} ${DBG} ${DEFINES} ${INCL} $^ -o $@

test:
ifeq (${DBG},-g)
	@valgrind --quiet --leak-check=full --show-leak-kinds=all ${P}/httpts -name "http-test-suite" -desc "test suite for http" -v
else
	@${P}/httpts -name "http-test-suite" -desc "test suite for http" -v
endif

install:

clean:
	@/bin/rm -rf ${OBJS} ${P}/httpts
