include ../../Makefile.constants

ifndef P
$(error P is not set)
endif

OBJS =  ${P}/net.o ${P}/addrinfo.o ${P}/ia.o ${P}/sa.o ${P}/host.o

INCL = ${INCLNET} ${INCLLOG} ${INCLCOM}

all: platform ${P}/libnet.a

platform:
	@test -d ${P} || mkdir ${P}

${P}/libnet.a: ${OBJS}
	${AR} ${ARFLAGS} $@ $^

${P}/%.o: %.cpp
	${CC} ${CFLAGS} ${LDFLAGS} ${DBG} ${DEFINES} ${INCL} $^ -o $@

install:

clean:
	@/bin/rm -rf ${OBJS} ${P}/libnet.a
